package sozgur;
// Generated 10.Tem.2013 23:52:42 by Hibernate Tools 3.2.1.GA



/**
 * Kaydet generated by hbm2java
 */
public class Kaydet  implements java.io.Serializable {


     private Integer id;
     private float sayi1;
     private float sayi2;
     private float sonuc;

    public Kaydet() {
    }

    public Kaydet(float sayi1, float sayi2, float sonuc) {
       this.sayi1 = sayi1;
       this.sayi2 = sayi2;
       this.sonuc = sonuc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public float getSayi1() {
        return this.sayi1;
    }
    
    public void setSayi1(float sayi1) {
        this.sayi1 = sayi1;
    }
    public float getSayi2() {
        return this.sayi2;
    }
    
    public void setSayi2(float sayi2) {
        this.sayi2 = sayi2;
    }
    public float getSonuc() {
        return this.sonuc;
    }
    
    public void setSonuc(float sonuc) {
        this.sonuc = sonuc;
    }




}


