package tugdev;
// Generated 14.Tem.2013 12:08:34 by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String ad;
     private String soyad;
     private int yas;

    public User() {
    }

    public User(String ad, String soyad, int yas) {
       this.ad = ad;
       this.soyad = soyad;
       this.yas = yas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }
    public int getYas() {
        return this.yas;
    }
    
    public void setYas(int yas) {
        this.yas = yas;
    }




}


