package pakettoplam;
// Generated 09.Tem.2013 14:44:44 by Hibernate Tools 3.2.1.GA



/**
 * Topla generated by hbm2java
 */
public class Topla  implements java.io.Serializable {


     private Integer id;
     private int sayi1;
     private int sayi2;
     private int sonuc;

    public Topla() {
    }

    public Topla(int sayi1, int sayi2, int sonuc) {
       this.sayi1 = sayi1;
       this.sayi2 = sayi2;
       this.sonuc = sonuc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSayi1() {
        return this.sayi1;
    }
    
    public void setSayi1(int sayi1) {
        this.sayi1 = sayi1;
    }
    public int getSayi2() {
        return this.sayi2;
    }
    
    public void setSayi2(int sayi2) {
        this.sayi2 = sayi2;
    }
    public int getSonuc() {
        return this.sonuc;
    }
    
    public void setSonuc(int sonuc) {
        this.sonuc = sonuc;
    }




}


